### ISSUE TITLE
about the handling of key value when 6 keys are existing in queue

### ISSUE THREAD

**Issue by zerobikappa** [firestaradmin/WorldEdit-No.1#2]
在处理按键的过程中你将第七个被按下的按键舍弃了。不过我试过我的键盘（不知道是不是只有我的键盘是这样的），发现虽然也是六键无冲，但如果按下第7第8个按键，电脑仍然是能输出的，所以我想可以设计成如果发现六个位置都满了的话，就将这个按键放在第六个位置。例如这样：

    //循环    只要ATKeyData数据包有空位则插入该键值，并且break。
    //如果六次循环完毕也没插，就将该按键替换进原本第六个按键的位置
    for(k = 0; k < 6; k++)
    {
        if(ATKeyData[k].ATKeyData == 0x00)//将按键AT值放入ATKeyData  Buffer
        {
                ATKeyData[k].ATKeyData = myKeyBoard_KeyMap_ATValue[i][j];
                ATKeyData[k].rowN = i;
                ATKeyData[k].colN = j;
                break;
        }
    }
    if(k==6)  //如果上面的for循环是正常退出的话k就等于6，如果是由于break而退出的话k就等于成功放入buffer的位置编号(0-5)
    {
        ATKeyData[5].ATKeyData = myKeyBoard_KeyMap_ATValue[i][j];
        ATKeyData[5].rowN = i;
        ATKeyData[5].colN = j;
    };

**Comment by firestaradmin** [comment]
都可以啦，按照自己的想法来
